const dOpts=(a,w)=>{let r=[a,...w].map(String).filter((x,i,z)=>z.indexOf(x)===i);for(const f of ['Güvenli davranırım.','Bir yetişkine haber veririm.','Gözlem yaparım.','Kaynakları dikkatli kullanırım.'])if(r.length<4&&!r.includes(f))r.push(f);return r.slice(0,4)},dQ=(p,v,a,w)=>[p,v,a,dOpts(a,w)];
const weather=[['Yağmur','🌧️'],['Kar','🌨️'],['Rüzgâr','💨'],['Sis','🌫️'],['Dolu','🧊'],['Güneşli hava','☀️'],['Bulutlu hava','☁️'],['Fırtına','⛈️'],['Gökkuşağı','🌈'],['Kırağı','❄️'],['Şimşek','⚡'],['Gök gürültüsü','🌩️'],['Sağanak','🌧️'],['Hafif yağmur','🌦️'],['Kuvvetli rüzgâr','🌬️'],['Sıcak hava','🌡️'],['Soğuk hava','🥶'],['Parçalı bulutlu hava','🌤️'],['Tipi','🌨️'],['Buzlanma','🧊'],['Çiy','💧'],['Kurak hava','🏜️'],['Nemli hava','💦'],['Serin hava','🍃'],['Açık hava','🌞']];
const seasons=['İlkbahar','Yaz','Sonbahar','Kış'];
const weatherPool=Array.from({length:100},(_,i)=>{let z=weather[i%25],k=Math.floor(i/25),season=seasons[i%4];if(k===0)return dQ(z[1]+' görseli hangi hava olayını veya hava durumunu gösterir?','🔎 Hava gözlemi',z[0],[weather[(i+4)%25][0],weather[(i+9)%25][0],weather[(i+14)%25][0]]);if(k===1)return dQ(z[0]+' gözlendiğinde hava günlüğüne ne kaydedilmelidir?','📔 Hava günlüğü','Tarih ve gözlenen hava olayı',['Yalnız sevdiğimiz renk','Tahmin edilen rastgele bilgi','Konuyla ilgisiz bir olay']);if(k===2)return dQ(season+' mevsiminde '+z[0].toLocaleLowerCase('tr-TR')+' görüldü. Bu durum için hangi yorum doğrudur?','🎡 Mevsim ve hava','Bir hava olayı farklı mevsimlerde de görülebilir.',['Her mevsimde hava tamamen aynıdır.','Bu hava olayı yalnız bir gün sürer.','Mevsimler hava olaylarından etkilenmez.']);return dQ(z[0]+' için güvenilir bilgi edinmenin en doğru yolu hangisidir?','📊 Minik meteorolog','Gözlem yapmak ve güvenilir hava tahminini incelemek',['Yalnızca rastgele tahmin etmek','Geçen yılın aynı gününü kesin kabul etmek','Arkadaşın söylediğini kontrol etmeden yazmak'])});
const directions=['Kuzey','Güney','Doğu','Batı'];
const directionPlaces=['Okul','Ev','Park','Kütüphane','Market','Hastane','Bahçe','Durak','Müze','Spor salonu','Fırın','Postane','Oyun alanı','Kırtasiye','Eczane','Sinema','Tiyatro','Havuz','Çeşme','Köprü','Orman','Göl','Tepe','Çiftlik','Kamp alanı'];
const directionPool=Array.from({length:100},(_,i)=>{let A=directionPlaces[i%25],B=directionPlaces[(i*7+3)%25],dir=directions[i%4],k=Math.floor(i/25);if(k===0)return dQ('Güneşin doğduğu yön temel alınırsa bu yön hangisidir?','🌅 Yön bulma','Doğu',['Batı','Kuzey','Güney']);if(k===1)return dQ('Güneşin battığı yön temel alınırsa bu yön hangisidir? '+A+' gözlem noktasındadır.','🌇 '+A,'Batı',['Doğu','Kuzey','Güney']);if(k===2)return dQ(B+', '+A+' konumunun '+dir.toLocaleLowerCase('tr-TR')+' yönündedir. '+A+' konumundan '+B+' konumuna hangi yöne gidilir?','🧭 '+A+' → '+B,dir,directions.filter(x=>x!==dir));return dQ(A+' çevresinde yönünü doğrulamak için en güvenilir araç hangisidir?','🧭 Doğa ve yön','Pusula',['Yalnız ağaçların yosunu','Rastgele bir tahmin','Bulutların biçimi'])});
const disasters=['Deprem','Sel','Yangın','Fırtına','Heyelan','Çığ','Orman yangını','Su baskını','Şiddetli dolu','Yıldırım','Kuvvetli rüzgâr','Bina yangını','Mutfak yangını','Elektrik yangını','Yoğun duman','Gaz kaçağı','Kıyı taşkını','Toprak kayması','Tipi','Aşırı sıcak','Aşırı soğuk','Kuraklık','Buzlanma','Şiddetli yağış','Hortum'];
const disasterPool=Array.from({length:100},(_,i)=>{let s=disasters[i%25],k=Math.floor(i/25);if(k===0)return dQ(s+' tehlikesinden önce alınabilecek uygun önlem hangisidir?','🛡️ Afete hazırlık','Aile afet planı hazırlamak ve güvenli davranışları öğrenmek',['Tehlikeyi önemsememek','Çıkış yollarını kapatmak','Acil çantayı boş bırakmak']);if(k===1)return dQ(s+' sırasında çocuk için en güvenli temel davranış hangisidir?','🚨 Güvenli davranış','Öğrenilen güvenlik kuralını uygulayıp yetişkin yönlendirmesini izlemek',['Tehlikeye yaklaşmak','Tek başına müdahale etmek','Merak için dışarı çıkmak']);if(k===2)return dQ(s+' sonrasında çevrede tehlike fark edilirse ne yapılmalıdır?','📞 Yardım isteme','Güvenli yerde kalıp yetişkine veya görevliye haber verilmelidir.',['Tehlikeli alana girilmelidir.','Hasarlı eşyalara dokunulmalıdır.','Bilgi gizlenmelidir.']);return dQ(s+' için acil durum çantasında hangisinin bulunması uygundur?','🎒 Hazırlık çantası','Su, temel ihtiyaçlar ve gerekli iletişim bilgileri',['Ağır oyuncak koleksiyonu','Gereksiz cam eşyalar','Bozulabilecek çok sayıda yiyecek'])});
const resources=['Su','Elektrik','Kâğıt','Ekmek','Yiyecek','Doğal gaz','Yakıt','Odun','Toprak','Temiz hava','Ormanlar','Madenler','Güneş enerjisi','Rüzgâr enerjisi','Piller','Plastik','Cam','Metal','Kıyafet','Okul araçları','Oyuncaklar','Kitaplar','Temizlik malzemesi','Isınma enerjisi','Ulaşım enerjisi'];
const savingPool=Array.from({length:100},(_,i)=>{let r=resources[i%25],k=Math.floor(i/25);if(k===0)return dQ(r+' kaynağını tasarruflu kullanmak için hangi davranış uygundur?','♻️ Tasarruf','İhtiyaç kadar kullanıp gereksiz tüketimden kaçınmak',['Gereğinden fazla kullanmak','Kullanılabilir olanı çöpe atmak','Kaynağı açık bırakmak']);if(k===1)return dQ(r+' israf edildiğinde hangi sonuç ortaya çıkabilir?','🌍 Kaynaklarımız','Doğal kaynaklar azalabilir ve çevre zarar görebilir.',['Kaynaklar kendiliğinden çoğalır.','Çevre her zaman temizlenir.','Tasarrufa gerek kalmaz.']);if(k===2)return dQ(r+' kullanıldıktan sonra yeniden değerlendirme mümkünse ne yapılmalıdır?','🔄 Yeniden kullanım','Uygun biçimde yeniden kullanmak veya geri dönüşüme ayırmak',['Doğrudan doğaya bırakmak','Karışık biçimde çöpe atmak','Kullanılabilirken yok etmek']);return dQ(r+' konusunda aile ve okulda tasarrufu artırmak için ne yapılabilir?','💡 Çözüm üret','Herkesin uygulayabileceği açık bir tasarruf kuralı belirlemek',['Kuralları yalnız bir kişinin uygulaması','İsrafı görmezden gelmek','Gereksiz tüketimi artırmak'])});
const sections=[
{code:'HB.2.5.1',color:'#347bc1',soft:'#e7f3ff',icon:'🌦️',title:'Hava Olayları ve Mevsimler',intro:'Hava olaylarını gözlemle, kaydet ve mevsimlerle ilişkilendir.',badge:'Hava Gözlemcisi Rozeti',games:[{id:'hava100',icon:'📔',title:'Minik Meteorolog',desc:'100 hava ve mevsim görevini tamamla.',q:weatherPool}]},
{code:'HB.2.5.2',color:'#6c55b8',soft:'#f1edff',icon:'🧭',title:'Yönümü Buluyorum',intro:'Ana yönleri, Güneş’i ve güvenilir yön bulma araçlarını kullan.',badge:'Yön Kâşifi Rozeti',games:[{id:'yon100',icon:'🧭',title:'Doğanın Pusulası',desc:'100 yön bulma sorusunu çöz.',q:directionPool}]},
{code:'HB.2.5.3',color:'#d95757',soft:'#ffeaea',icon:'🚨',title:'Afetlere Karşı Önlem Alalım',intro:'Afet öncesi, sırası ve sonrasında güvenli davranışları uygula.',badge:'Afet Bilinci Rozeti',games:[{id:'afet100',icon:'🎒',title:'Güvenli Yaşam Ekibi',desc:'100 afet hazırlığı ve güvenlik görevini tamamla.',q:disasterPool}]},
{code:'HB.2.5.4',color:'#2e9668',soft:'#e7f8ef',icon:'♻️',title:'Tasarruflu Kullanalım',intro:'Doğal kaynakları ihtiyaç kadar kullan, yeniden değerlendir ve israfı önle.',badge:'Kaynak Koruyucusu Rozeti',games:[{id:'tasarruf100',icon:'💧',title:'Tasarruf Kahramanı',desc:'100 kaynak koruma görevini çöz.',q:savingPool}]}
];
let state=JSON.parse(localStorage.getItem("doga-cevre-progress")||'{"score":0,"wins":{}}');
const worlds=document.getElementById("worlds"),modal=document.getElementById("modal");
let game=null,qi=0,correct=0,locked=false;

function render(){
 worlds.innerHTML=sections.map((s,si)=>`<article class="world" style="--c:${s.color};--soft:${s.soft}">
 <div class="world-head"><div class="world-icon">${s.icon}</div><div><div class="code">${s.code}</div><h2>${si+1}. Bölüm · ${s.title}</h2><div>${s.badge} ${sectionWon(s)?"✅":"🔒"}</div></div></div>
 <div class="intro"><b>Konuyu keşfet</b>${s.intro}</div>
 <div class="cards">${s.games.map(g=>`<button class="card" data-id="${g.id}" style="--c:${s.color}"><span class="emoji">${g.icon}</span><h3>${g.title}</h3><p>${g.desc}</p><strong>${state.wins[g.id]?"Tamamlandı ✓":"Oyunu aç →"}</strong></button>`).join("")}</div></article>`).join("");
 document.querySelectorAll(".card").forEach(b=>b.onclick=()=>start(findGame(b.dataset.id)));
 updateProgress();
}
function findGame(id){for(const s of sections){const g=s.games.find(x=>x.id===id);if(g)return {...g,section:s}}}
function sectionWon(s){return s.games.every(g=>state.wins[g.id])}
function updateProgress(){document.getElementById("stars").textContent=state.score;document.getElementById("badges").textContent=sections.filter(sectionWon).length+"/4"}
function start(g){game={...g,q:[...g.q].sort(()=>Math.random()-.5)};qi=0;correct=0;locked=false;modal.hidden=false;document.body.style.overflow="hidden";showQ()}
function showQ(){
 const q=game.q[qi];locked=false;
 document.getElementById("gameHead").innerHTML=`<div class="game-title">${game.icon} ${game.title}</div><div class="game-meta">${game.section.code} · ${correct*10} puan</div>`;
 document.getElementById("bar").style.width=(qi/game.q.length*100)+"%";
 document.getElementById("question").innerHTML=`<div class="qno">GÖREV ${qi+1} / ${game.q.length}</div><div class="prompt">${q[0]}</div><div class="scene">${q[1]}</div>`;
 const opts=[...q[3]].sort(()=>Math.random()-.5);
 document.getElementById("answers").innerHTML=opts.map(a=>`<button class="answer">${a}</button>`).join("");
 document.getElementById("feedback").textContent="";document.getElementById("next").hidden=true;
 document.querySelectorAll(".answer").forEach(b=>b.onclick=()=>answer(b,q[2]));
}
function answer(btn,right){if(locked)return;locked=true;document.querySelectorAll(".answer").forEach(b=>{b.disabled=true;if(b.textContent===String(right))b.classList.add("good")});if(btn.textContent===String(right)){correct++;btn.classList.add("good");document.getElementById("feedback").textContent="Harika! Doğru cevap. +10 puan ⭐"}else{btn.classList.add("bad");document.getElementById("feedback").textContent="Birlikte öğrendik! Doğru cevap: "+right}document.getElementById("next").hidden=false}
document.getElementById("next").onclick=()=>{qi++;if(qi<game.q.length)showQ();else finish()};
function finish(){const won=correct>=80;if(won&&!state.wins[game.id]){state.wins[game.id]=true;state.score+=correct*10}else if(!state.wins[game.id])state.score+=correct*10;localStorage.setItem("doga-cevre-progress",JSON.stringify(state));document.getElementById("bar").style.width="100%";document.getElementById("question").innerHTML=`<div class="result"><div class="cup">${won?"🏆":"🌱"}</div><h2>${won?"Görev tamamlandı!":"Bir kez daha deneyelim!"}</h2><p>100 sorudan ${correct} tanesini doğru cevapladın. ${won?"Bu oyunun yıldızını kazandın!":"80 doğruya ulaştığında oyunu tamamlayacaksın."}</p><button class="play-again" id="again">${won?"Oyunlara dön":"Yeniden oyna"}</button></div>`;document.getElementById("answers").innerHTML="";document.getElementById("feedback").textContent="";document.getElementById("next").hidden=true;document.getElementById("again").onclick=()=>won?closeGame():start(game);render()}
function closeGame(){modal.hidden=true;document.body.style.overflow="";render()}
document.getElementById("close").onclick=closeGame;modal.onclick=e=>{if(e.target===modal)closeGame()};
document.getElementById("reset").onclick=()=>{if(confirm("Tüm puan ve rozetler sıfırlansın mı?")){state={score:0,wins:{}};localStorage.setItem("doga-cevre-progress",JSON.stringify(state));render()}};
render();